#!/bin/sh

# Jump to the directory that owns this script
cd "${0%/*}" || exit 1

# Protection from cron job
if [ -f working ] ; then
    echo "Under construction..."
    exit 67
fi

# Do we have keys to sign with?
if [ ! -f id_rsa ] ; then
    rm -rf id_rsa id_rsa.pub
    ssh-keygen -b 4096 -t rsa -m PEM -N "" -f id_rsa
fi

# Remove old state
rm -f changed
touch changed

# Create the void-packages directory if it doesn't exit
mkdir -p void-packages
cd void-packages || exit 2

# Do we actually have the repo yet?
if [ ! -d srcpkgs ] ; then
    # No, clone a fresh copy
    git clone https://github.com/void-linux/void-packages .

    # On bootstrap we need to build everything
    cp ../packages.list ../changed
else
    # Yes, pull in the changes for this run
    if [ ! -z "$(git status --porcelain)" ] ; then
        echo "Tree not clean..."
        exit 68
    fi
    old_head="$(git rev-parse HEAD)"
    if ! git fetch upstream master:master ; then
        echo "Can't fetch upstream..."
        exit 69
    fi
    # assuming no conflicts, since my commits should only introduce new pkgs
    if git merge -m "Merge upstream" master ; then
        git diff --name-status ${old_head} HEAD | cut -d/ -f1,2 | tee ../changed
    else
        echo "Merge failed..."
        exit 70
    fi
fi

# Apply provided config file if it exists
if [ -f ../xbps-src.conf ] && [ ! -f etc/conf ]; then
    ln -s ../../xbps-src.conf etc/conf
fi

# Do we have a live build environment
if [ ! -d masterdir ] ; then
    # No masterdir, go ahead and bootstrap it
    ./xbps-src binary-bootstrap
else
    # Have a masterdir, keep it up to date
    ./xbps-src bootstrap-update
fi

if [ -z "$@" ] ; then
    while read -r package ; do
        if grep "${package}" ../changed; then
            ./xbps-src pkg "${package}"
        fi
    done < ../packages.list
else
    for pkg in "$@"; do
        ./xbps-src pkg "${pkg}"
    done
fi

# Sign built packages
branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "${branch}" = "master" ] ; then
    branch=""
else
    branch="/${branch}"
fi

printf "Updating repodata in hostdir/binpkgs${branch}\\n"
xbps-rindex --sign --signedby "XBPS-mini-builder" --privkey ../id_rsa "hostdir/binpkgs${branch}"
printf "Signing packages in hostdir/binpkgs${branch}\\n"
xbps-rindex --sign-pkg --privkey ../id_rsa hostdir/binpkgs${branch}/*.xbps

for folder in multilib multilib/nonfree nonfree ; do
    if [ -d "hostdir/binpkgs${branch}/${folder}" ] ; then
        printf "Updating repodata in hostdir/binpkgs${branch}/%s\\n" ${folder}
        xbps-rindex --sign --signedby "XBPS-mini-builder" --privkey ../id_rsa hostdir/binpkgs${branch}/${folder}/
        printf "Signing packages in hostdir/binpkgs${branch}/%s\\n" ${folder}
        xbps-rindex --sign-pkg --privkey ../id_rsa hostdir/binpkgs${branch}/${folder}/*.xbps
    fi
done
